DOMAIN = "ha_zyxel"
DEFAULT_NAME = "Zyxel Device"
DEFAULT_HOST = "https://192.168.1.1"
DEFAULT_USERNAME = "admin"
DEFAULT_SCAN_INTERVAL = 30
DEFAULT_REQUEST_TIMEOUT = 5
ERROR_BACKOFF_INTERVAL = 60

CONF_HOST = "host"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"

CONF_SCAN_INTERVAL = "scan_interval"
CONF_CONSIDER_HOME = "consider_home"
CONF_TRACK_ALL = "track_all"
CONF_CLIENT_DIAGNOSTICS = "client_diagnostics"
CONF_EXPOSE_ALL_ROUTER_SENSORS = "expose_all_router_sensors"
CONF_ADVANCED_CELLULAR_DIAGNOSTICS = "advanced_cellular_diagnostics"
CONF_SENSITIVE_CELLULAR_IDENTIFIERS = "sensitive_cellular_identifiers"
CONF_SENSITIVE_CREDENTIAL_DIAGNOSTICS = "sensitive_credential_diagnostics"
DEFAULT_CONSIDER_HOME = 300
DEFAULT_TRACK_ALL = False
DEFAULT_CLIENT_DIAGNOSTICS = False
DEFAULT_EXPOSE_ALL_ROUTER_SENSORS = False
DEFAULT_ADVANCED_CELLULAR_DIAGNOSTICS = False
DEFAULT_SENSITIVE_CELLULAR_IDENTIFIERS = False
DEFAULT_SENSITIVE_CREDENTIAL_DIAGNOSTICS = False
