DOMAIN = "ha_zyxel"
DEFAULT_NAME = "Zyxel Device"
DEFAULT_HOST = "https://192.168.1.1"
DEFAULT_USERNAME = "admin"
DEFAULT_SCAN_INTERVAL = 30
DEFAULT_REQUEST_TIMEOUT = 5

CONF_HOST = "host"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"

CONF_SCAN_INTERVAL = "scan_interval"
CONF_CONSIDER_HOME = "consider_home"
CONF_TRACK_ALL = "track_all"
DEFAULT_CONSIDER_HOME = 300
DEFAULT_TRACK_ALL = False
